flask_app/user/models.py
from flask_login import UserMixin

from flask_app import login_manager, mongo


class User(UserMixin):

    def __init__(self, username, password, email, first_name, last_name):
        self.username = username
        self.password = password
        self.email = email
        self.first_name = first_name
        self.last_name = last_name

    def get_id(self):
        return self.username


@login_manager.user_loader
def load_user(user_id):
    found = mongo.db.auth.find_one({'username': user_id})
    return User(found['username'], found['password'], found['email'],
                found['firstName'], found['lastName']
                )

flask_app/__init__.py
import json
import os
import pathlib

from flask import Flask, request, session, send_from_directory
from flask_babel import Babel
from flask_bcrypt import Bcrypt
from flask_cors import CORS
from flask_login import LoginManager
from flask_pymongo import PyMongo
from flask_mail import Mail

config_json_path = os.path.join(str(pathlib.Path.cwd()), 'flask_app/config.json')
mongo = PyMongo()
b_crypt = Bcrypt()

login_manager = LoginManager()
cors = CORS(resources={r"/api/*": {"origins": "*"}})

app = Flask(__name__)

# i18n
babel = Babel(app)

with open(config_json_path) as f:
    config = json.load(f)

mail_settings = {
    "MAIL_SERVER": 'smtp.gmail.com',
    "MAIL_PORT": 587,
    "MAIL_USE_TLS": True,
    "MAIL_USE_SSL": False,
    "MAIL_USERNAME": config.get('EMAIL_USER'),
    "MAIL_PASSWORD": config.get('EMAIL_PASSWORD'),
    "MAIL_DEFAULT_SENDER": config.get('EMAIL_USER'),
}

app.config.update(mail_settings)
mail = Mail(app)


@babel.localeselector
def get_locale():
    # if the user has set up the language manually it will be stored in the session,
    # so we use the locale from the user settings
    try:
        language = session['language']
    except KeyError:
        language = None
    if language is not None:
        return language
    return request.accept_languages.best_match(app.config['LANGUAGES'].keys())


def create_app(config_json=config_json_path):
    # global config
    app.config.from_json(config_json, silent=False)
    cors.init_app(app)
    mongo.init_app(app)
    b_crypt.init_app(app)
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    # blueprints
    from flask_app.compute.routes import compute
    from flask_app.auth.routes import auth
    from flask_app.user.routes import user
    from flask_app.view.routes import view
    app.register_blueprint(compute)
    app.register_blueprint(auth)
    app.register_blueprint(user)
    app.register_blueprint(view)

    return app


@app.context_processor
def inject_conf_var():
    return dict(
        AVAILABLE_LANGUAGES=config['LANGUAGES'],
        CURRENT_LANGUAGE=session.get('language', request.accept_languages.best_match(config['LANGUAGES'].keys())))


@app.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join(app.root_path, 'static'),
                               'favicon.ico', mimetype='image/vnd.microsoft.icon')

flask_app/compute/routes.py
from datetime import datetime
from pathlib import Path

from flask import Blueprint, request, jsonify, current_app, send_file, render_template
from flask_babel import gettext
from flask_mail import Message
from oct2py import Oct2PyError

from flask_app import config
from flask_app import mongo, mail
from flask_app.auth.service import key_required
from flask_app.compute.service import MatLab
from flask_app.util.export import DBExporter
from flask_app.util.logger import Logger

compute = Blueprint('compute', __name__)
logger = Logger(mongo.db, 'log')


@compute.route('/api/data/<function_name>', methods=['GET'])
@key_required
def get_octave_data(function_name):
    param_r = request.args.get('r')
    param_init1 = request.args.get('init1')
    param_init2 = request.args.get('init2')
    try:
        if not param_r:
            return 'Parameter value r is missing', 400

        r = float(param_r)

        if not param_init1:
            param_init1 = 0
        if not param_init2:
            param_init2 = 0

        init1 = float(param_init1)
        init2 = float(param_init2)

        mat_lab = MatLab(current_app.config['MATLAB_FORMULAE_PATH'])
        result = None
        try:
            if function_name == 'plane':
                result = mat_lab.compute_plane_data(r, init1, init2)
            elif function_name == 'ball':
                result = mat_lab.compute_ball_data(r, init1, init2)
            elif function_name == 'suspension':
                result = mat_lab.compute_suspension_data(r, init1, init2)
            elif function_name == 'pendulum':
                result = mat_lab.compute_pendulum_data(r, init1, init2)
            else:
                return f'Matlab function name {function_name} not found', 400

            logger.log(function_name + f'(r={r})', datetime.utcnow(), 'SUCCESS')
        except Oct2PyError as e:
            logger.log(function_name + f'(r={r})', datetime.utcnow(), 'ERROR', str(e))
    except ValueError:
        return 'Invalid parameter value', 400
    if result:
        return jsonify(result)


@compute.route('/api/cli', methods=['POST'])
@key_required
def octave_cli():
    commands = request.data
    if commands:
        try:
            result = str(MatLab.use_cli(commands.decode('utf-8')))
            logger.log(commands.decode('utf-8'), datetime.utcnow(), 'SUCCESS')
            return result
        except Oct2PyError as e:
            logger.log(commands.decode('utf-8'), datetime.utcnow(), 'ERROR', str(e))
            return str(e), 400
    else:
        return 'No commands inserted in body', 400


@compute.route('/api/export/csv', methods=['GET'])
@key_required
def csv_export():
    exporter = DBExporter(mongo.db, 'log')
    exporter.all_to_csv()
    return send_file(str(Path(__file__).parent.absolute()) + '/../static/export.csv', 'export.csv')


@compute.route('/api/export/pdf', methods=['GET'])
@key_required
def pdf_export():
    exporter = DBExporter(mongo.db, 'log')
    exporter.all_to_pdf()
    return send_file(str(Path(__file__).parent.absolute()) + '/../static/export.pdf', 'export.pdf')


# @compute.route('/api/export/stat', methods=['GET'])
# @key_required
# def stat_export():
#     exporter = DBExporter(mongo.db, 'log')
#     return exporter.compute_stats()
#     # return send_file(str(Path(__file__).parent.absolute()) + '/../static/stat.pdf', 'stat.pdf')

@compute.route('/mail')
@key_required
def send_mail():
    recipient = request.args.get('email')
    pdf = request.args.get('pdf') == 'true'
    csv = request.args.get('csv') == 'true'

    exporter = DBExporter(mongo.db, 'log')
    msg = Message(subject=gettext(u'Export štatistík z aplikácie Octavia Proxy'),
                  recipients=[recipient])
    msg.html = render_template('email-template.html')
    if pdf:
        exporter.all_to_pdf()
        with open(config['STATIC_PATH'] + 'stats.pdf', 'rb') as fp:
            msg.attach("statistics.pdf", "application/pdf", fp.read())
    if csv:
        exporter.all_to_csv()
        with open(config['STATIC_PATH'] + 'export.csv', 'rb') as fp:
            msg.attach("statistics.csv", "text/csv", fp.read())
    mail.send(msg)

    return 'success'

flask_app/user/routes.py
from flask import Blueprint, jsonify, session, redirect
from flask_login import login_required, current_user

user = Blueprint('user', __name__)


@user.route('/profile')
@login_required
def profile():
    return jsonify(vars(current_user))


@user.route('/language/<language>')
def set_language(language=None):
    session['language'] = language
    return redirect('/')

flask_app/view/routes.py
from flask import Blueprint, render_template
from flask_login import login_required
from flask_app.util.export import DBExporter
from flask_app import mongo


view = Blueprint('view', __name__)


@view.route('/')
@login_required
def profile():
    return render_template('index.jinja2')


@view.route('/terminal')
@login_required
def console():
    return render_template('terminal.jinja2')


@view.route('/stats')
@login_required
def stats():
    exporter = DBExporter(mongo.db, 'log')
    return render_template('stats.jinja2', stats=exporter.compute_stats())

flask_app/templates/base.jinja
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    {# vsetky dependencie je mozno idealne natahovat tu #}
    <link href="{{ url_for('static', filename='node_modules/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <script href="{{ url_for('static', filename='node_modules/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <title>{% block title %}{% endblock %} Webtech2 final assigment </title>
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">WEBTE2 octave proxy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="page-footer font-small blue">
        <div class="footer-copyright text-center py-3">
            {% block footer %}
            &copy; Copyright 2020 by Andrej Fula, Pavol Dudak, Peter Hajduk & Peter Vigh.
            {% endblock %}
        </div>
    </footer>
</body>

</html>

flask_app/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
        {# vsetky dependencie je mozno idealne natahovat tu #}
        <link href="{{ url_for('static', filename='node_modules/bootstrap/dist/css/bootstrap.min.css') }}"
              rel="stylesheet">
        <link href="{{ url_for('static', filename='node_modules/bootstrap-slider/dist/css/bootstrap-slider.css') }}"
              rel="stylesheet">
        <link href="{{ url_for('static', filename='styles/style.css') }}"
              rel="stylesheet">
        <title>{% block title %}{% endblock %} {{ _('WebTech2 Finálne Zadanie') }} </title>
    {% endblock %}
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
    <a class="navbar-brand" href="/">{{ _('WEBTE2 Octavia Proxy') }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/">{{ _('Simulácie') }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="terminal">{{ _('Octave terminál') }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="stats"> {{ _('Štatistiky') }}</a>
            </li>
        </ul>
        <a class="logout-btn btn btn-md" target="_blank"
           href="https://trello.com/b/iS2wU2s0/webtech2"> {{ _('Rozdelenie práce') }} </a>
        <a class="logout-btn btn btn-md" target="_blank"
           href="https://app.swaggerhub.com/apis/Malph1/WebTe2FinalAPIDoc/1.0.0">{{ _('API dokumentácia') }}</a>
        <form class="form-inline my-2 my-lg-0" action="/logout" method="post">
            <input type="submit" class="logout-btn btn btn-md" value={{ _('Odhlásiť sa') }}>
        </form>
        <div class="btn-group">
            <button class="logout-btn btn btn-md btn-dropdown mr-5" type="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                {{ CURRENT_LANGUAGE }}
                <img style="width: 1rem" src="../static/assets/images/{{ CURRENT_LANGUAGE }}.svg"
                     alt="{{ CURRENT_LANGUAGE }} flag">
            </button>
            <div class="dropdown-menu">
                {# hehe, dirty shit ako keby to pisal prvak tu nebudeme tolerovat#}
                {% for language in AVAILABLE_LANGUAGES.items() %}
                    {% if CURRENT_LANGUAGE == language[0] %}
                        <span class="dropdown-item">{{ language[1] }}
                        <img style="width: 1rem" src="../static/assets/images/{{ language[0] }}.svg"
                             alt="{{ language[1] }} flag"> </span>
                    {% else %}
                        <a href="{{ url_for('user.set_language', language=language[0]) }}"
                           class="dropdown-item">{{ language[1] }}
                            <img style="width: 1rem" src="../static/assets/images/{{ language[0] }}.svg"
                                 alt="{{ language[1] }} flag"> </a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</nav>

<div id="content">
    {% block content %}
    {% endblock %}
</div>

<footer class="page-footer font-small blue">
    <div class="footer-copyright text-center py-3">
        {% block footer %}
            &copy; Copyright 2020 by Andrej Fula, Pavol Dudak, Peter Hajduk a Péter Vigh.
        {% endblock %}
    </div>
</footer>
<script src="{{ url_for('static', filename='node_modules/plotly.js-dist/plotly.js') }}"></script>
<script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='node_modules/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='node_modules/bootstrap-slider/dist/bootstrap-slider.js') }}"></script>
<script src="{{ url_for('static', filename='node_modules/pixi.js/dist/pixi.js') }}"></script>
<script src="{{ url_for('static', filename='./plotly-app.js') }}"></script>
<script src="{{ url_for('static', filename='./terminal-app.js') }}"></script>
</body>

</html>

flask_app/templates/email-template.html
<h3>{{ _('Export štatistík z aplikácie Octavia Proxy') }}
{#    Statistics export from Octavia Proxy application#}
</h3>
<p>{{ _('Priložený súbor obsahuje štatistiky volania Octave príkazov, počet volaní a podobné dáta') }}
{#    Statistics in attached file/files represents called octave commands, number of calls and similar data.#}
</p>
<hr>
<footer style="font-size: x-small">
    {{ _('Táto správa bola vygenerovaná automaticky. Neodpovedajte na ňu.
     Ak potrebujete bližšie informácia, máte bohužiaľ smolu') }}
{#    This message was generated automatically. Don't respond to it. If you need further instructions, you are#}
{#    unfortunately on your own.#}
</footer>

{#    todo remove english translations once they are used in messages.po    #}
{#    todo try to add support for multi-valued strings (main paragraph)   #}

flask_app/templates/formBase.jinja2
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    {% block head %}
        <link href="{{ url_for('static', filename='node_modules/bootstrap/dist/css/bootstrap.min.css') }}"
              rel="stylesheet">
        <link href="{{ url_for('static', filename='./styles/form-style.css') }}"
              rel="stylesheet">
        <title>{% block title %}{% endblock %} {{ _('WebTech2 Finalné Zadanie') }} </title>
    {% endblock %}
</head>

<body>
<div class="h-100">
    <div class="w-100 d-flex justify-content-center main-bar shadow">
        <span style="font-size: 40px" class="d-flex flex-column m-auto octavia-header">{{ _('Octavia proxy') }}</span>
        <div class="btn-group">
            <div class="language-switch">
                {% for language in AVAILABLE_LANGUAGES.items() %}
                    {% if CURRENT_LANGUAGE != language[0] %}
                        <a href="{{ url_for('user.set_language', language=language[0]) }}"
                           class="language-switch-link">{{ language[1] }}
                            <img style="width: 1rem" src="../static/assets/images/{{ language[0] }}.svg"
                                 alt="{{ language[1] }} flag"> </a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="container mt-5">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-6 col-10">
                <div id="login-box" class="col-md-12 shadow">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>

    <footer class="page-footer font-small blue">
        <div class="footer-copyright text-center py-3">
            {% block footer %}
                &copy; Copyright 2020 by Andrej Fula, Pavol Dudak, Peter Hajduk & Peter Vigh.
            {% endblock %}
        </div>
    </footer>
</div>
</body>

</html>

flask_app/templates/index.jinja
{# takto si importovat makra #}
{% from 'macros/hello_firends.jinja' import hello_friends %}

{% extends "base.jinja" %}
{% block title %}Index{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}

{# do tokto bloku sa insertuju vsetky data #}
{% block content %}
    <div class="container">
        <h1 class="display-3 text-center">Balkón - Láska, popiči láska</h1>
        <p class="text-center">
            Kde sa feti tu sa feti murko beha doplašeny <br>
            kde su fetyy? (tralalala) <br>
            Kde sa feti tu sa feti murko beha doplašeny <br>
            kde su fetyy?(kde sú fety?)rychlo dajte fety. <br>
        </p>
        <div class="row justify-content-center">
            {# makro je ako funkcia ktora ma svoje argumenty #}
            {{ hello_friends("Zakova", "Fuck you") }}
        </div>
    </div>        
{% endblock %}

flask_app/templates/index.jinja2
{# takto si importovat makra #}
{% extends "base.jinja2" %}
{% from 'macros/hello_firends.jinja2' import hello_friends %}

{% block title %}Octavia simulation | {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}

{# do tokto bloku sa insertuju vsetky data #}
{% block content %}
    <div class="container simulation-content">
        <div class="row">
            <div class="col-md-4 col-sm-12">
                <select id="data-options" class="custom-select">
                    <option selected hidden disabled>{{ _('Vyber si graf :') }}</option>
                </select>
            </div>
            <div class="col-md-4 col-sm-12">
                <span id="parameter-slider-label">Parameter:</span>
                <input type="range" class="form-control-range" id="parameter-slider" data-slider-min="-1"
                       data-slider-max="1" data-slider-id="parameter-slider-data"
                       data-slider-step="0.05" data-slider-value="0.2">
            </div>
            <div class="col-md-4 col-sm-12">
                <span id="speed-slider-label">Speed:</span>
                <input type="range" class="form-control-range" id="speed-slider" data-slider-min="0"
                       data-slider-max="2" data-slider-id="speed-slider-data"
                       data-slider-step="0.1" data-slider-value="1">
            </div>
        </div>
        <button type="button" class="btn btn-primary btn-block top-margin" id="show">{{ _('Zobraz graf') }}</button>
        <div class="row">
            <div class="col-12 col-lg-7">
                <div id="canvas"></div>
            </div>
            <div class="col-12 col-lg-5">
                <div id="chart"></div>
            </div>
        </div>
    </div>
{% endblock %}

flask_app/templates/login.jinja2
{% extends "formBase.jinja2" %}

{% block content %}
    <form id="login-form" class="form" action="" method="post">
        <h3 class="text-center text-info">{{ _('Prihlásenie') }}</h3>
        <div class="form-group">
            {{ form.email.label(class_="text-info") }}
            {{ form.email(class_="form-control") }}
            {% if form.email.errors %}
                <ul class="errors">
                    {% for error in form.email.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password.label(class_="text-info") }}
            {{ form.password(class_="form-control") }}
            {% if form.password.errors %}
                <ul class="errors">
                    {% for error in form.password.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="form-check">
            {{ form.remember(class_="form-check-input") }}
            {{ form.remember.label(class_="text-info form-check-label") }}
        </div>
        <div class="form-group d-flex pt-2 pb-2 link-container">
            <input type="submit" name="submit" class="btn btn-info btn-md" value={{ _('Prihlásiť sa') }}>
            <a href="/register" class="link text-info">{{ _('Ešte nemáte účet?') }}</a>
        </div>
    </form>

{% endblock %}

flask_app/templates/macros/hello_firends.jinja
{% macro hello_friends(name, greeting='Hello') -%}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ greeting }} {{ name }}</h5>
            <p class="card-text">Today we are going to learn how to do webtech2 bullshit.</p>        
        </div>
    </div>
{%- endmacro %}

flask_app/templates/macros/hello_firends.jinja2
{% macro hello_friends(name, greeting='Hello') -%}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ greeting }} {{ name }}</h5>
            <p class="card-text">Today we are going to learn how to do webtech2 'things'.</p>
        </div>
    </div>
{%- endmacro %}

flask_app/templates/register.jinja2
{% extends "formBase.jinja2" %}

{% block content %}
    <form id="login-form" class="form" action="" method="post">
        <h3 class="text-center text-info">{{ _('Registrácia') }}</h3>
        <div class="form-group">
            {{ form.username.label(class_="text-info") }}
            {{ form.username(class_="form-control") }}
            {% if form.username.errors %}
                <ul class="errors">
                    {% for error in form.username.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.firstName.label(class_="text-info") }}
            {{ form.firstName(class_="form-control") }}
            {% if form.firstName.errors %}
                <ul class="errors">
                    {% for error in form.firstName.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.lastName.label(class_="text-info") }}
            {{ form.lastName(class_="form-control") }}
            {% if form.lastName.errors %}
                <ul class="errors">
                    {% for error in form.lastName.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.email.label(class_="text-info") }}
            {{ form.email(class_="form-control") }}
            {% if form.email.errors %}
                <ul class="errors">
                    {% for error in form.email.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password.label(class_="text-info") }}
            {{ form.password(class_="form-control") }}
            {% if form.password.errors %}
                <ul class="errors">
                    {% for error in form.password.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.passwordRepeat.label(class_="text-info") }}
            {{ form.passwordRepeat(class_="form-control") }}
            {% if form.passwordRepeat.errors %}
                <ul class="errors">
                    {% for error in form.passwordRepeat.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="form-group d-flex pt-2 pb-2 link-container">
            <input type="submit" name="submit" class="btn btn-info btn-md" value={{ _('Vytvoriť účet') }}>
            <a href="/login" class="text-info link">{{_('Už máte účet?')}}</a>
        </div>
    </form>

{% endblock %}

flask_app/templates/stats.jinja2
{% extends "base.jinja2" %}

{% block title %}Octavia simulation | {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}

{% block content %}
    <div class="container">
        <form class="form-inline" id="mail-form">
            <div class="btn-toolbar mb-3 top-margin" role="toolbar" aria-label="Toolbar with button groups">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text" id="btnGroupAddon">{{ _('Odoslať štatistiky na:') }}</div>
                    </div>
                    <input type="email" class="form-control" placeholder="{{ _('Emailová adresa') }}"
                           aria-label="User email address" aria-describedby="btnGroupAddon" id="user-email">
                </div>
                <div class="btn-group mr-2 left-margin" role="group" aria-label="First group">
                    <label class="btn btn-outline-success">
                        <input type="checkbox" autocomplete="off" hidden id="csv"> CSV
                    </label>
                    <label class="btn btn-outline-danger">
                        <input type="checkbox" autocomplete="off" hidden id="pdf"> PDF
                    </label>
                </div>
                <input type="submit" class="btn btn-dark btn-md" value="{{ _('Odoslať') }}" id="send-mail-btn" disabled>
                <span id="mail-success-message" class="left-margin response-text">
                    {{ _('Mail úspešne odoslaný') }}</span>
                <span id="mail-error-message" class="left-margin response-text">
                    {{ _('Odosielanie mailu zlyhalo') }}</span>
            </div>
        </form>

        <h1>{{ _('Celkovo volaní :') }} {{ stats[2] }}</h1>
        <h2>{{ _('Úspešných :') }} {{ stats[1]['SUCCESS'] }}</h2>
        <h2>{{ _('Neúspešných:') }} {{ stats[1]['ERROR'] }}</h2>
            <table class="table">
                <thead>
                    <tr>
                    <th scope="col">{{ _('Príkaz') }}</th>
                    <th scope="col">{{ _('Volanie') }}</th>
                    </tr>
                </thead>
            <tbody>
            {% for k, v in stats[0]|dictsort(by='value', reverse=True) %}
                <tr>
                    <th>{{ k }}</th>
                    <td>{{ v }}</td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}

flask_app/templates/terminal.jinja2
{% extends "base.jinja2" %}

{% block title %}Octavia console | {% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}

{# do tokto bloku sa insertuju vsetky data #}
{% block content %}
    <div class="center">
        <h1 class="terminal-header">Octavia terminal</h1>
        <div class="terminal-wrapper">
            <div class="terminal-output"></div>
            <form id="command-form" autocomplete="off" role="form" data-toggle="validator">
                <span class="command-prefix"></span>
                <input class="terminal-input" type="text" id="command-input" spellcheck="false" hidden>
                <input type="submit" hidden>
            </form>
        </div>
    </div>
{% endblock %}